adjectives = [
    "ace",
    "amazing",
    "astonishing",
    "astounding",
    "awesome",
    "badass",
    "beautiful",
    "bedazzling",
    "breathtaking",
    "brilliant",
    ("captivating", "k"),
    ("careless", "k"),
    ("cautious", "k"),
    ("charming", "ch"),
    ("cheeky", "ch"),
    ("chic", "sh"),
    ("churlish", "ch"),
    ("classy", "cl"),
    ("clever", "cl"),
    ("clumsy", "cl"),
    ("cool", "k"),
    ("crabby", "cr"),
    ("cranky", "cr"),
    ("creepy", "cr"),
    ("crucial", "cr"),
    ("cryptic", "cr"),
    "dandy",
    "dazzling",
    "delightful",
    "divine",
    "doozie",
    "epic",
    "excellent",
    "exceptional",
    "exquisite",
    "extraordinary",
    "fabulous",
    "fantastic",
    "fantabulous",
    "fine",
    "finest",
    "first-class",
    "first-rate",
    ("flaky", "fl"),
    ("flamboyant", "fl"),
    ("flawless", "fl"),
    "funkadelic",
    "galloping",
    ("geometric", "j"),
    "glorious",
    ("gnarly", "n"),
    "good",
    ("grand", "gr"),
    ("great", "gr"),
    ("groovy", "gr"),
    ("groundbreaking", "gr"),
    "handy",
    "heroic",
    "hungry",
    "hunky-dory",
    "impeccable",
    "impressive",
    "incredible",
    "jaded",
    "jaunty",
    "jealous",
    "keen",
    "kickass",
    "kingly",
    "kooky",
    "kryptonian",
    "laudable",
    "legendary",
    "lovely",
    "luminous",
    "magnificent",
    "majestic",
    "marvelous",
    "mathematical",
    "mind-blowing",
    "neat",
    "outstanding",
    "peachy",
    "perfect",
    "phenomenal",
    "pioneering",
    "polished",
    "posh",
    "praiseworthy",
    "premium",
    "priceless",
    "prime",
    "primo",
    "rad",
    "remarkable",
    "riveting",
    "saucy",
    ("scrappy", "sc"),
    "sensational",
    ("shabby", "sh"),
    ("shady", "sh"),
    ("shaven", "sh"),
    ("shining", "sh"),
    ("sketchy", "sk"),
    ("skeptical", "sk"),
    ("skittish", "sk"),
    "slick",
    "smashing",
    "solid",
    ("spacy", "sp"),
    ("spectacular", "sp"),
    ("splendid", "sp"),
    ("splendiferous", "sp"),
    ("spooky", "sp"),
    ("stellar", "st"),
    ("striking", "st"),
    ("stunning", "st"),
    ("stupendous", "st"),
    ("stylish", "st"),
    "sublime",
    "super",
    "super-duper",
    "super-excellent",
    "superb",
    "superior",
    "supreme",
    "sweet",
    "swell",
    "terrific",
    "tiptop",
    "top-notch",
    "transcendent",
    "tremendous",
    "ultimate",
    "unreal",
    "valiant",
    "versatile",
    "well-made",
    "wicked",
    "wonderful",
    "wondrous",
    "world-class",
    "zany",
    "zazzy",
    "zealous",
    "zesty",
]

animals = [
    "aardvark",
    "albatross",
    "alligator",
    "alpaca",
    "ant",
    "anteater",
    "antelope",
    "ape",
    "armadillo",
    "baboon",
    "badger",
    "barracuda",
    "bat",
    "bear",
    "beaver",
    "bee",
    "bison",
    "boar",
    "buffalo",
    "butterfly",
    ("camel", "k"),
    ("capybara", "k"),
    ("caribou", "k"),
    ("cassowary", "k"),
    ("cat", "k"),
    ("caterpillar", "k"),
    ("cattle", "k"),
    ("cheetah", "ch"),
    ("chicken", "ch"),
    ("chimpanzee", "ch"),
    ("chinchilla", "ch"),
    ("clam", "cl"),
    ("cobra", "k"),
    ("cockroach", "k"),
    ("cod", "k"),
    ("cormorant", "k"),
    ("coyote", "k"),
    ("crab", "cr"),
    ("crane", "cr"),
    ("crocodile", "cr"),
    ("crow", "cr"),
    "deer",
    "dinosaur",
    "dog",
    "dogfish",
    "dolphin",
    "donkey",
    "dove",
    "dragonfly",
    "duck",
    "dugong",
    "eagle",
    "echidna",
    "eel",
    "elephant",
    "elk",
    "emu",
    "falcon",
    "ferret",
    "finch",
    "fish",
    ("flamingo", "fl"),
    ("fly", "fl"),
    "fox",
    "frog",
    "gazelle",
    ("gerbil", "j"),
    ("giraffe", "j"),
    ("gnat", "n"),
    "gnu",
    "goat",
    "goose",
    "goldfinch",
    "goldfish",
    "gorilla",
    ("grasshopper", "gr"),
    ("grouse", "gr"),
    "guinea-fowl",
    "guinea-pig",
    "gull",
    "hamster",
    "hare",
    "hawk",
    "hedgehog",
    "heron",
    "herring",
    "hippopotamus",
    "hornet",
    "horse",
    "human",
    "hummingbird",
    "hyena",
    "ibex",
    "ibis",
    "jackal",
    "jaguar",
    "jay",
    "jellyfish",
    "kangaroo",
    "kingfisher",
    "koala",
    "komodo-dragon",
    "kookabura",
    "lapwing",
    "lark",
    "lemur",
    "leopard",
    "lion",
    "llama",
    "lobster",
    "locust",
    "louse",
    "lyrebird",
    "magpie",
    "mallard",
    "manatee",
    "mandrill",
    "mantis",
    "marten",
    "meerkat",
    "mink",
    "mole",
    "mongoose",
    "monkey",
    "moose",
    "mouse",
    "mosquito",
    "mule",
    "narwhal",
    "newt",
    "nightingale",
    "octopus",
    "opossum",
    "oryx",
    "ostrich",
    "otter",
    "owl",
    "ox",
    "oyster",
    "panther",
    "parrot",
    "partridge",
    "peafowl",
    "pelican",
    "penguin",
    ("pheasant", "f"),
    "pig",
    "pigeon",
    "polar-bear",
    "pony",
    "porcupine",
    "porpoise",
    "prairie-dog",
    ("quail", "k"),
    "rabbit",
    "raccoon",
    "rail",
    "ram",
    "rat",
    "raven",
    "reindeer",
    "rhinoceros",
    "rook",
    "salamander",
    "salmon",
    "sand-dollar",
    "sandpiper",
    "sardine",
    "scorpion",
    "sea-lion",
    "sea-urchin",
    "seahorse",
    "seal",
    ("shark", "sh"),
    ("sheep", "sh"),
    ("shrew", "sh"),
    ("skunk", "sk"),
    "snail",
    "snake",
    ("sparrow", "sp"),
    ("spider", "sp"),
    ("spoonbill", "sp"),
    ("squid", "sk"),
    ("squirrel", "sk"),
    ("starling", "st"),
    ("stingray", "st"),
    ("stinkbug", "st"),
    ("stork", "st"),
    "swallow",
    "swan",
    "tapir",
    "termite",
    "tiger",
    "toad",
    "trout",
    "turkey",
    "turtle",
    "vicuña",
    "viper",
    "vulture",
    "wallaby",
    "walrus",
    "wasp",
    "water-buffalo",
    "weasel",
    "whale",
    "wolf",
    "wolverine",
    "wombat",
    "woodcock",
    "woodpecker",
    "worm",
    ("wren", "r"),
    "yak",
    "zebra"
]

import random

def generate():
    animal = random.choice(animals)

    if type(animal) is tuple:
        animal, animal_initial = animal
    else:
        animal_initial = animal[0]

    def match(adjective):
        if type(adjective) is tuple:
            adjective, adjective_initial = adjective
        else:
            adjective_initial = adjective[0]

        return adjective_initial == animal_initial

    try:
        adjective = random.choice([x for x in adjectives if match(x)])
    except IndexError:
        adjective = random.choice(adjectives)

    if type(adjective) is tuple:
        adjective, _ = adjective

    return "-".join((adjective, animal))

if __name__ == "__main__":
    for i in range(300):
        print(generate())
