#!/usr/bin/env python3

from topia.termextract import extract
from haystack import *

extractor = extract.TermExtractor()

with open("data/data.text", "r") as f:
    results = extractor(f.read())

    results.sort(key=lambda x: x[1])
    
    for result in results:
        print(result)
