#!/bin/sh
#
# chkconfig: 2345 80 30
# description: A daemon that sends info about this system to a QMF broker
# sesame: Sesame daemon
# processname: sesame
# pidfile: /var/run/sesame.pid
#

# Sanity checks.
[ -x /usr/bin/sesame ] || exit 0

# Source function library.
. /etc/rc.d/init.d/functions

# so we can rearrange this easily
processname=sesame
servicename=sesame

[ -f /etc/sysconfig/$servicename ] && . /etc/sysconfig/$servicename

RETVAL=0

start() {
    echo -n $"Starting Sesame daemon: "
    daemon --user sesame --check $servicename $processname $SESAME_OPTIONS\&
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$servicename
}

stop() {
    echo -n $"Stopping Sesame daemon: "

    killproc $servicename -TERM
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm -f /var/lock/subsys/$servicename
        rm -f /var/run/sesame.pid
    fi
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $processname
        RETVAL=$?
        ;;
    restart)
        stop
	sleep 3
        start
        ;;
    condrestart)
        if [ -f /var/lock/subsys/$servicename ]; then
            stop
	    sleep 3
            start
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart}"
        ;;
esac
exit $RETVAL
