#!/usr/bin/python

import sys

from lowboy.director import *

director = Director()

id_a = 1
id_b = 2

director.call_constructor(id_a, "proton", "Messenger")
director.call_constructor(id_b, "proton", "Messenger")

director.call_method(id_a, "start")
director.call_method(id_b, "start")

director.call_method(id_a, "stop")
director.call_method(id_b, "stop")

director.marshal(sys.stdout)
