#!/usr/bin/python3

from plano import *

#ENV["MESSAGING_SERVICE_PORT"] = "5672"

enable_logging(level="warn")

sender = None
receiver = None

try:
    call("mvn clean package")

    with working_env(HTTP_HOST="localhost", HTTP_PORT="8081"):
        sender = start_process("java -jar sender/target/hello-world-jms-openshift-sender-1.0.0-SNAPSHOT-jar-with-dependencies.jar")

    with working_env(HTTP_HOST="localhost", HTTP_PORT="8082"):
        receiver = start_process("java -jar receiver/target/hello-world-jms-openshift-receiver-1.0.0-SNAPSHOT-jar-with-dependencies.jar")

    sleep(1)

    call("curl -X POST -d \"hello 1\" -H \"Content-type: text/plain\" http://localhost:8081/api/send", quiet=True)
    call("curl -X POST -d \"hello 2\" -H \"Content-type: text/plain\" http://localhost:8081/api/send", quiet=True)
    call("curl -X POST http://localhost:8082/api/receive", quiet=True)
    call("curl -X POST http://localhost:8082/api/receive", quiet=True)
    call("curl -X POST http://localhost:8082/api/receive", quiet=True)
    call("curl http://localhost:8081/api/health", quiet=True)
    call("curl http://localhost:8082/api/health", quiet=True)
finally:
    terminate_process(sender)
    terminate_process(receiver)
