.PHONY: build

build:
	mkdir -p ${TUBADEV_BUILD}/projectx/lib
	cp jars/ProjectX.jar ${TUBADEV_BUILD}/projectx
	cp jars/commons-net-1.3.0.jar ${TUBADEV_BUILD}/projectx/lib
	cp jars/jakarta-oro-2.0.8.jar ${TUBADEV_BUILD}/projectx/lib
	cp bin/projectx ${TUBADEV_BUILD}/bin/projectx
