#!/usr/bin/python3

from plano import *

#ENV["MESSAGING_SERVICE_PORT"] = "5672"

enable_logging(level="notice")

frontend = None
processor = None

try:
    with working_env(HTTP_HOST="localhost", HTTP_PORT="8081"):
        frontend = start_process("java -jar frontend/target/word-cloud-jms-kubernetes-frontend-1.0.0-SNAPSHOT-jar-with-dependencies.jar")

    with working_env(HTTP_HOST="localhost", HTTP_PORT="8082"):
        processor = start_process("java -jar processor/target/word-cloud-jms-kubernetes-processor-1.0.0-SNAPSHOT-jar-with-dependencies.jar")

    while True:
        try:
            http_get("http://localhost:8081/api/ready")
            http_get("http://localhost:8082/api/ready")

            break
        except CalledProcessError:
            sleep(0.2)

    while True:
        sleep(1)
except KeyboardInterrupt:
    pass
finally:
    terminate_process(frontend)
    terminate_process(processor)
