#!/usr/bin/python3

from plano import *

ENV["MESSAGING_SERVICE_PORT"] = "5672"

enable_logging(level="debug")

worker_1 = None
worker_2 = None

try:
    with working_dir("worker"):
        worker_1 = start_process("java -Dswarm.port.offset=2 -jar target/wfswarm-messaging-work-queue-worker-1-SNAPSHOT-swarm.jar")
        worker_2 = start_process("java -Dswarm.port.offset=3 -jar target/wfswarm-messaging-work-queue-worker-1-SNAPSHOT-swarm.jar")

    with working_dir("frontend"):
        call("java -Dswarm.port.offset=1 -jar target/wfswarm-messaging-work-queue-frontend-1-SNAPSHOT-swarm.jar")
except KeyboardInterrupt:
    pass
except CalledProcessError:
    terminate_process(worker_1)
    terminate_process(worker_2)
