/* Generated By:JavaCC: Do not edit this line. WidgetParserConstants.java */
package wooly.lang;

public interface WidgetParserConstants {

  int EOF = 0;
  int SEMI = 6;
  int COLON = 7;
  int LCURLY = 8;
  int RCURLY = 9;
  int LPAREN = 10;
  int RPAREN = 11;
  int TQUOTE = 12;
  int INTEGER = 13;
  int BOOLEAN = 14;
  int WIDGET = 15;
  int PAGE = 16;
  int TEXT = 17;
  int MODES = 18;
  int TABS = 19;
  int TAB = 20;
  int URL = 21;
  int STRING = 22;
  int ID = 23;
  int DIGIT = 24;
  int CH = 25;
  int SEP = 26;
  int COMMENT = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\";\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\\\"\\\"\"",
    "<INTEGER>",
    "<BOOLEAN>",
    "\"widget\"",
    "\"page\"",
    "\"text\"",
    "\"modes\"",
    "\"tabs\"",
    "\"tab\"",
    "\"url\"",
    "<STRING>",
    "<ID>",
    "<DIGIT>",
    "<CH>",
    "<SEP>",
    "<COMMENT>",
  };

}
