#!/bin/bash -ex

source ../common/library.bash
source ../common/qpid-stable.bash

script-init

cd "${SOURCE_PATH}/cpp"

./bootstrap
./configure --prefix="$INSTALL_PATH"
make -j$(core-count)
make install

if [[ "$(distro)" == "rhel" && "$(release)" == "4" ]]; then
    install -d "${INSTALL_PATH}/include/qpid-boost/boost/detail"
    install -d "${INSTALL_PATH}/include/qpid-boost/boost/ptr_container/detail"
    install -d "${INSTALL_PATH}/include/qpid-boost/boost/parameter/aux_/python"
    install -d "${INSTALL_PATH}/include/qpid-boost/boost/parameter/aux_/preprocessor"
    install -pm 0644 src/boost/*.hpp "${INSTALL_PATH}/include/qpid-boost/boost"
    install -pm 0644 src/boost/detail/*.hpp "${INSTALL_PATH}/include/qpid-boost/boost/detail"
    install -pm 0644 src/boost/ptr_container/*.hpp "${INSTALL_PATH}/include/qpid-boost/boost/ptr_container"
    install -pm 0644 src/boost/ptr_container/detail/*.hpp "${INSTALL_PATH}/include/qpid-boost/boost/ptr_container/detail"
    install -pm 0644 src/boost/parameter/*.hpp "${INSTALL_PATH}/include/qpid-boost/boost/parameter"
    install -pm 0644 src/boost/parameter/aux_/*.hpp "${INSTALL_PATH}/include/qpid-boost/boost/parameter/aux_"
    install -pm 0644 src/boost/parameter/aux_/python/*.hpp "${INSTALL_PATH}/include/qpid-boost/boost/parameter/aux_/python"
    install -pm 0644 src/boost/parameter/aux_/preprocessor/*.hpp "${INSTALL_PATH}/include/qpid-boost/boost/parameter/aux_/preprocessor"
fi
