/* Generated By:JavaCC: Do not edit this line. LentilParserConstants.java */
package lentil;

public interface LentilParserConstants {

  int EOF = 0;
  int SEMI = 5;
  int COLON = 6;
  int LCURLY = 7;
  int RCURLY = 8;
  int LPAREN = 9;
  int RPAREN = 10;
  int INTEGER = 11;
  int BOOLEAN = 12;
  int PACKAGE = 13;
  int CLASS = 14;
  int FIELD = 15;
  int KEY = 16;
  int STRING = 17;
  int ID = 18;
  int DIGIT = 19;
  int CH = 20;
  int SEP = 21;
  int COMMENT = 22;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<INTEGER>",
    "<BOOLEAN>",
    "\"package\"",
    "\"class\"",
    "\"field\"",
    "\"key\"",
    "<STRING>",
    "<ID>",
    "<DIGIT>",
    "<CH>",
    "<SEP>",
    "<COMMENT>",
  };

}
