#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import print_function

import sys

from plano import *

module = sys.argv[1]
output_dir = join(current_dir(), "testalot-output")
source_url = "http://git-wip-us.apache.org/repos/asf/qpid-{}.git".format(module)
repo_dir = join(output_dir, "repo")

if not exists(repo_dir):
    call("git clone --mirror '{}' {}", source_url, repo_dir)

with working_dir(repo_dir):
    call("git fetch --all")
    output = call_for_output("git rev-list --since={4.weeks.ago} HEAD")
    
for commit in reversed(output.splitlines()):
    test_dir = join(output_dir, commit)
    
    if exists(test_dir):
        notice("Already tested {}", commit)
        continue
        
    make_dir(test_dir)

    notice("Testing {}", commit)

    log_file = join(test_dir, "log.txt")

    cmd = "rivet build {}@{} --output '{}' &> '{}'"
    call(cmd, module, commit, test_dir, log_file, shell=True)

    call("tail -n 1 '{}'", log_file)
