#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import print_function

from plano import *

call("rivet env --init-only")
call("rivet info all --init-only")
call("rivet fetch qpid-proton --init-only")
call("rivet build qpid-cpp qpid-dispatch --init-only")
call("rivet install qpid-proton@HEAD --init-only")
call("rivet release qpid-cpp@abc123 qpid-dispatch@xyz789 --init-only")
call("rivet test all --release-tag alpha --init-only")
call("rivet clean all --output /tmp/cat --prefix /tmp/dog --init-only")
