SOURCE_DIR=$PWD
BUILD_DIR=$SOURCE_DIR/build
INSTALL_DIR=$SOURCE_DIR/install

export SOURCE_DIR BUILD_DIR INSTALL_DIR

CROQUET_HOME=$INSTALL_DIR/lib/croquet

export CROQUET_HOME

PATH=$INSTALL_DIR/bin:$SOURCE_DIR/scripts:$PATH

export PATH
