/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __tuba_dvb_Driver__
#define __tuba_dvb_Driver__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_tuba_dvb_Driver_tune (JNIEnv *env, jclass, jstring, jint);
JNIEXPORT jint JNICALL Java_tuba_dvb_Driver_add_1video_1filter (JNIEnv *env, jclass, jstring, jint);
JNIEXPORT jint JNICALL Java_tuba_dvb_Driver_add_1audio_1filter (JNIEnv *env, jclass, jstring, jint);
JNIEXPORT jint JNICALL Java_tuba_dvb_Driver_close (JNIEnv *env, jclass, jint);

#ifdef __cplusplus
}
#endif

#endif /* __tuba_dvb_Driver__ */
