apiVersion: v1
kind: Template
metadata:
  name: wfswarm-messaging-work-queue-frontend
  annotations:
    iconClass: icon-jboss
    tags: wildfly-swarm, java, microservice, messaging
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    description: The WildFly Swarm Work Queue Mission demonstrates scalable task processing using messaging
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/ssorj/wfswarm-messaging-work-queue
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: frontend
  required: true
- name: ARTIFACT_COPY_ARGS
  description: Syntax to be used to copy uberjar files to the target directory
  displayName: Copy Args
  value: '*-swarm.jar'
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: MAVEN_MIRROR_URL
  description: Maven Nexus Repository to be used during build phase
  displayName:
  required: false
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: wfswarm-messaging-work-queue-frontend
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime-wfswarm-messaging-work-queue-frontend
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wfswarm-messaging-work-queue-frontend
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: wfswarm-messaging-work-queue-frontend:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-wfswarm-messaging-work-queue-frontend:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "--projects resource-adapter,${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: ARTIFACT_COPY_ARGS
          value: "${ARTIFACT_COPY_ARGS}"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: wfswarm-messaging-work-queue-frontend
    name: wfswarm-messaging-work-queue-frontend
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: wfswarm-messaging-work-queue-frontend
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: wfswarm-messaging-work-queue-frontend
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GC_MAX_METASPACE_SIZE
            value: "200"
          envFrom:
            - configMapRef:
                name: messaging-service
          image: wfswarm-messaging-work-queue-frontend:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: wfswarm-messaging-work-queue-frontend
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - wfswarm-messaging-work-queue-frontend
        from:
          kind: ImageStreamTag
          name: wfswarm-messaging-work-queue-frontend:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wfswarm-messaging-work-queue-frontend
    name: wfswarm-messaging-work-queue-frontend
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: wfswarm-messaging-work-queue-frontend
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: wfswarm-messaging-work-queue-frontend
    name: frontend
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: wfswarm-messaging-work-queue-frontend
