#!/usr/bin/env python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from pencil import *

result = nvl("alpha", "beta")
assert result == "alpha"

result = nvl(None, "beta")
assert result == "beta"

result = nvl("alpha", "beta", "[{}]")
assert result == "[alpha]"

result = shorten(None, 5)
assert result == ""

result = shorten("1234567890", 5)
assert result == "12345"

result = shorten("1234567890", 20)
assert result == "1234567890"

result = init_cap(None)
assert result == ""

result = init_cap("alpha")
assert result == "Alpha"
